### ISSUE TITLE
Allow CSS setting is not kept on upgrade

### ISSUE THREAD

**Issue by xmgz** [YunoHost-Apps/gotosocial_ynh#76]
### Describe the bug

most instance settings are corretly set to previous values after upgrading, but "allow personal css" is not. 

### Context

gotosocial 0.8.0 (it happens since previous versions too) in latest stable YNH server (11.1.17, 64bit, etc.)

### Steps to reproduce

- set "allow css" to _true_ in yunohost gotosocial config panel.
- upgrade gotosocial

### Expected behavior

**true** (or value set) should persist on upgrading as other values in config panel do

![image](https://user-images.githubusercontent.com/704948/231336061-9a54306b-ae4f-430a-8162-8c5499bde877.png)

Thank you.

**Comment by OniriCorpe** [comment]
Hi!

This issue was fixed yesterday in the v0.8.0~ynh3 ^w^

To be sure, I just tested with a modified configuration, including the custom css parameter, and I forced an update on my test instance, and the parameters were well preserved

![A screenshot of the config panel on the part relating to the accounts, with a modified configuration, including that on the custom CSS](https://user-images.githubusercontent.com/6963387/231496099-4ea9d643-920e-418d-be8a-282b1288022b.png)

So, everything should be fine now 

If you want to test this, you can do it with this command:
`yunohost app upgrade gotosocial -u https://github.com/YunoHost-Apps/gotosocial_ynh/tree/master --force`

**Comment by OniriCorpe** [comment]
I close, do not hesitate to answer if the bug is still present for you with the last version
